name: KaMenu
version: '${version}'
main: org.katacr.kamenu.KaMenu
api-version: '1.16'
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Vault
  - PlayerPoints
  - ItemsAdder
  - Oraxen
  - CraftEngine
  - floodgate
commands:
  kamenu:
    description: KaMenu 主指令
    usage: /kamenu open <menuId>
    permission: kamenu.admin
    aliases: [km, menu]
permissions:
  kamenu.admin:
    description: 允许玩家使用菜单全部功能
    default: op
