name: KaMenu
version: '1.5.0'
main: org.katacr.kamenu.KaMenu
api-version: '1.21'
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  kamenu:
    description: KaMenu 主指令
    usage: /kamenu open <menuId>
    permission: kamenu.admin
    aliases: [km, menu]
permissions:
  kamenu.admin:
    description: 允许玩家使用菜单全部功能
    default: op
